name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        # List of output destinations (format: type=local,dest=path)
        outputs: type='local',dest=./

          
